# -*- coding: utf-8 -*-
"""Map

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T802HFXcpOt9ydg_yBtNQ5npqCiTeIxI
"""

!pip install chart_studio
import pandas as pd
import chart_studio.plotly as py
import plotly.graph_objects as go

## Read the cvs file
df1=pd.read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv", sep=",")

## Take a look to df1
df1.head()

import plotly.express as px

fig = px.scatter_geo(df1, lat="Lat",lon="Long", size=((df1["4/5/20"])),
                     hover_name="Country/Region", color=(df1["4/5/20"])/1000,
                     projection="natural earth")
fig.show()